# parameters
nc: 1  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3, [1024, False]],  # 9

   [-4, 1, Conv, [64, 6, 2, 2]],  # 10
   [-1, 1, Conv, [128, 3, 2]],  # 11
   [-1, 3, C3, [128]],          # 12
   [-1, 1, Conv, [256, 3, 2]],  # 13
   [-1, 9, C3, [256]],          # 114
   [-1, 1, Conv, [512, 3, 2]],  # 15
   [-1, 9, C3, [512]],          #16
   [-1, 1, Conv, [1024, 3, 2]],  #17
   [-1, 1, SPP, [1024, [5, 9, 13]]], #18
   [-1, 3, C3, [1024, False]],  # 19

   [-6, 1, IWM, [[64,64], 2]],   #20    # downsample_size[64,64]
   [-6, 1, EFM, [3]],   #21
   
   [[4,14,20,21], 1, TransformerFusionBlock, [256, 20, 20]],    # 22 two stream fuse
   [[6,16,20,21], 1, TransformerFusionBlock, [512, 16, 16]],    # 23 two stream fuse
   [[9,19,20,21], 1, TransformerFusionBlock, [1024, 10, 10]],    # 24 two stream fuse
  ]
   
# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],  #25
   [-1, 1, nn.Upsample, [None, 2, 'nearest']], #26
   [[-1, 23], 1, Concat, [1]],  # 27
   [-1, 3, C3, [512, False]],  # 28

   [-1, 1, Conv, [256, 1, 1]],  #29
   [-1, 1, nn.Upsample, [None, 2, 'nearest']], #30
   [[-1, 22], 1, Concat, [1]],  # 31
   [-1, 3, C3, [256, False]],  # 32

   [-1, 1, Conv, [256, 3, 2]], #33
   [[-1, 29], 1, Concat, [1]],  # 34
   [-1, 3, C3, [512, False]],  # 35

   [-1, 1, Conv, [512, 3, 2]], #36
   [[-1, 25], 1, Concat, [1]],  # 37
   [-1, 3, C3, [1024, False]],  # 38

   [[32, 35, 38], 1, Detect, [nc, anchors]],  # 39
  ]
